export const data = {
  works: [
    {
      filter: "React",
      id: "movie",
      img: "https://github.com/hyemin12/react-dashboard-app2/blob/master/public/img/portfolio/movieReact.png?raw=true",
      title: "영화검색사이트",
      describtion: "",
      date: "2022-03-08",
      tool: [],
      features: [],
      git: "https://github.com/hyemin12/react-movie-app",
      url: "https://react-movie-app-1f5ff8.netlify.app/",
    },
    {
      filter: "Vanilla JS",
      id: "moment",
      img: "https://github.com/hyemin12/react-dashboard-app2/blob/master/public/img/portfolio/momentJS.png?raw=true",
      title: "크롬 앱",
      describtion:
        "노마드코더의 바닐라JS 크롬 앱을 클론 코딩하였다. 이름을 입력하면 사용이 가능하다. 날씨 정보, 랜덤으로 나오는 명언, 투두 작성이 가능하다.",
      date: "2022-02-21",
      tool: ["git-pahge"],
      features: [
        "1. open weather api를 활용한 날씨 정보 확인",
        "2. local storage의 username 값을 확인하여 로그인 / 홈 화면을 나타냄",
        "3. 페이지가 새로고침될 때마다 새로운 명언 & 배경이미지가 나타남",
        "4. 투두 리스트 작성",
      ],
      git: "https://github.com/hyemin12/vanillaJS-chrome-app",
      url: "https://hyemin12.github.io/vanillaJS-chrome-app/",
    },
    {
      filter: "Typescript",
      id: "tsc-todo",
      img: "https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FollCV%2FbtrEiwzPwYw%2Fm4aORom1lbpxrnd4NKpK70%2Fimg.png",
      title: "투두리스트",
      describtion: "",
      date: "2022-03-15",
      tool: [],
      features: [],
      git: "https://github.com/hyemin12/typescript-todo-app",
      url: "https://effulgent-pastelito-13b327.netlify.app/",
    },

    {
      filter: "Vanilla JS",
      id: "starbucks",
      img: "https://github.com/hyemin12/react-dashboard-app2/blob/master/public/img/portfolio/starbucks.png?raw=true",
      title: "starbucks 2017",
      describtion:
        "스타벅스 홈페이지를 클론 코딩하였다. 메인페이지와 로그인페이지로 이루어져 있다.",
      date: "2021-05-22",
      tool: [],
      features: [],
      git: "https://github.com/hyemin12/vanilla-starbucks-app",
      url: "https://starbucks-responsive-app-ee135b.netlify.app",
    },
    {
      filter: "Vanilla JS",
      id: "wordle",
      img: "https://github.com/hyemin12/react-dashboard-app2/blob/master/public/img/portfolio/wordleJS.png?raw=true",
      title: "Wordle 게임",
      describtion:
        "요즘 인기가 많은 단어를 맞추는 게임 wordle을 자바스크립트로만으로 구현한 프로젝트. 게임방법은 단어를 입력하고, Enter 버튼을 눌러 제출하기. 제출 시 각 타일의 색상이 변경되어 정답 단어에 얼마나 가까웠는지를 보여줌 ",
      date: "2022-03-20",
      tool: [],
      features: [
        "1. 키보드를 누르면 해당 값이 칸에 입력되고, 제출 시 채점됨 ",
        "2. 밝은 모드 / 어두운 모드로 모드 선택 가능",
      ],
      git: "https://github.com/hyemin12/vanillaJS-wordle-app",
      url: "https://hyemin12.github.io/vanillaJS-wordle-app/",
    },
    {
      filter: "React",
      id: "dashboard",
      img: "https://github.com/hyemin12/react-dashboard-app2/blob/master/public/img/portfolio/dashboardReact.png?raw=true",
      title: "대시보드",
      describtion:
        "다양한 API를 통해 정보를 가져오고, 해야할 일 목록 작성, 음악 플레이 등 다양한 작업을 할 수 있는 대쉬보드다. 개인 포트폴리오 페이지에서 포트폴리오도 확인 가능하다 ",
      date: "2022-03-20",
      tool: [],
      features: [
        "1. 키보드를 누르면 해당 값이 칸에 입력되고, 제출 시 채점됨 ",
        "2. 밝은 모드 / 어두운 모드로 모드 선택 가능",
      ],
      git: "https://github.com/hyemin12/react-dashboard-app2",
      url: "https://lucid-yonath-d614bb.netlify.app/",
    },
    {
      filter: "Vanilla JS",
      id: "paint",
      img: "https://github.com/hyemin12/react-dashboard-app2/blob/master/public/img/portfolio/paintJs.png?raw=true",
      title: "그림판",
      describtion:
        "노마드코더의 바닐라JS 그림판을 클론 코딩하였다. 캔버스에서 그림을 그릴 수 있으며, 이미지를 저장할 수 있다. ",
      date: "2022-02-22",
      tool: [],
      features: [
        "1. 그리기 모드 / 채우기(페인트) 모드 선택 가능 ",
        "2. 브러쉬 크기 및 색상 선택 가능",
        "3. save 버튼을 통해 그린 이미지 저장 가능",
      ],
      git: "https://github.com/hyemin12/vanillaJS-paint-app",
      url: "https://hyemin12.github.io/vanillaJS-paint-app/",
    },

    {
      filter: "jQuery",
      id: "stranger",
      img: "https://github.com/hyemin12/react-dashboard-app2/blob/master/public/img/portfolio/stranger.png?raw=true",
      title: "비밀의 숲2 프로모션",
      describtion: "",
      date: "2020-08-15",
      tool: [],
      features: [],
      git: "https://github.com/hyemin12/web-design-portfolio/01Stranger2/",
      url: "https://hyemin12.github.io/web-design-portfolio/01Stranger2/",
    },
    // {
    //   filter: "React",
    //   id: "twitter",
    //   img: "https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FZhFQN%2FbtrEZedyP5T%2F9ANH2jcfgq4kdbXA98FKQK%2Fimg.png",
    //   title: "트위터 클론 코딩",
    //   describtion: "",
    //   date: "2021-04-25",
    //   tool: [],
    //   features: [],
    //   git: "https://github.com/hyemin12/react-firebase-twitter",
    //   url: "",
    // },
    {
      filter: "React",
      id: "gomintalk",
      img: "https://github.com/hyemin12/react-dashboard-app2/blob/master/public/img/portfolio/gominTalk.png?raw=true",
      title: "리슨 클론 코딩",
      describtion:
        "요즘 뜨고 있는 Lysn bubble을 클론코딩하였다. 모바일 버전만 제공하기때문에, 550px 이상에서는 화면을 줄여달라는 화면만 표시된다. scss 패키지를 이용해서 css를 작성하였다. 프로필창에서 친구를 클릭하면 프로필 이미지 화면이 나타나고, 채팅을 보낼 수 있다.",
      date: "2022-05-20",
      tool: [],
      features: [],
      git: "https://github.com/hyemin12/gomin-talk-app",
      url: "https://wizardly-hermann-7fecb3.netlify.app/",
    },
    {
      filter: "ect",
      id: "lottecard",
      img: "https://github.com/hyemin12/react-dashboard-app2/blob/master/public/img/portfolio/lottecard.png?raw=true",
      title: "롯데카드 프로모션",
      describtion:
        "가정의 달을 맞아 롯데카드 기프트카드 판매 촉진 및 이벤트 홍보의 프로모션 페이지를 디자인하였다. 아기자기한 일러스트 이미지를 사용하여 사랑스러운 분위기를 표현하였으며, 롯데카드에서 자주 사용하는 핑크-블루 톤과 캐릭터를 사용하여 롯데카드 배너 느낌을 연출하였다.",
      date: "2020-05-27",
      tool: ["Photoshop"],

      features: [],
      url: "https://github.com/hyemin12/react-dashboard-app2/blob/master/public/img/portfolio/lottecard2.jpg?raw=true",
    },
    {
      filter: "ect",
      id: "travel",
      img: "https://github.com/hyemin12/react-dashboard-app2/blob/master/public/img/portfolio/travel.png?raw=true",
      title: "여행사 프로모션",
      describtion:
        "여행 SNS 공유 이벤트 참여 촉진 및 홍보의 프로모션 페이지를 디자인하였다. 전체적인 컨셉을 부다페스트로 설정하여 부다페스트 관련 이미지들을 사용하였고,그랜드 부다페스트호텔 포스터에 사용된 핑크-보라계열 색을 사용하여 부다페스트 느낌을 연출하였다.",
      date: "2020-03-20",
      tool: ["Photoshop"],

      features: [],
      url: "https://github.com/hyemin12/react-dashboard-app2/blob/master/public/img/portfolio/travel2.jpg?raw=true",
    },
    {
      filter: "jQuery",
      id: "melon",
      img: "https://github.com/hyemin12/react-dashboard-app2/blob/master/public/img/portfolio/melon.png?raw=true",
      title: "음악스트리밍 멜론",
      describtion: "",
      date: "2020-07-21",
      tool: ["Photoshop"],

      features: [],
      git: "https://github.com/hyemin12/web-design-portfolio/04Melon/",
      url: "https://hyemin12.github.io/web-design-portfolio/04Melon/",
    },
    {
      filter: "ect",
      id: "responsive1",
      img: "https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FnNaYu%2FbtrEjMWeqmn%2FFY8MF38rQJ0JmgYh21e4Sk%2Fimg.png",
      title: "반응형 사이트 - readOnly",
      describtion: "",
      date: "2022-04-12",
      tool: [],
      features: [],
      git: "https://github.com/hyemin12/responsive-webstie-readOnly",
      url: "https://hyemin12.github.io/responsive-webstie-readOnly/",
    },
    {
      filter: "ect",
      id: "responsive2",
      img: "https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fc2Np9y%2FbtrEkpzHQeG%2FfmDxkuNz8rnNygRWnfhSb1%2Fimg.png",
      title: "반응형 사이트 - massively",
      describtion: "",
      date: "2022-04-12",
      tool: [],
      features: [],
      git: "https://github.com/hyemin12/responsive-webstie-massively",
      url: "https://hyemin12.github.io/responsive-webstie-massively/",
    },
    {
      filter: "ect",
      id: "responsive3",
      img: "https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FkHK94%2FbtrEiOfVoFZ%2FKpWkikhALdpeBlVfyRFLr1%2Fimg.png",
      title: "반응형 사이트 - funny Flakes",
      describtion: "",
      date: "2022-04-10",
      tool: [],
      features: [],
      git: "https://github.com/hyemin12/responsive-webstie-funnyFlakes",
      url: "https://hyemin12.github.io/responsive-webstie-funnyFlakes/",
    },
  ],
  social: [
    { id: "social_github", url: "https://github.com/hyemin12" },
    { id: "social_blog", url: "https://hyemin-12.tistory.com/" },
  ],
};
